---
platform: linux

inputs:
  - name: bosh-community-ci-infra
  - name: paused-pipelines

params:
  CONCOURSE_URL:
  CONCOURSE_USERNAME: ((concourse_ci_user.username))
  CONCOURSE_PASSWORD: ((concourse_ci_user.password))

run:
  path: bosh-community-ci-infra/bosh-concourse/tasks/deploy-concourse/unpause-all-pipelines.sh
