#!/bin/bash

if ! kubectl get ns test 2>/dev/null; then
  cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Namespace
metadata:
  name: concourse
  labels:
    quarks.cloudfoundry.org/monitored: concourse
EOF
fi
