---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.30.0
directories:
- path: config/credhub/_ytt_lib/credhub
  contents:
  - path: .
    git:
      url: https://github.com/cloudfoundry-incubator/credhub
      ref: efe8a24
    includePaths:
    - kubernetes/**/*
- path: config/uaa/_ytt_lib/uaa
  contents:
  - path: .
    git:
      url: https://github.com/cloudfoundry/uaa
      ref: v75.1.0
    includePaths:
    - k8s/templates/**/*
# START delete when https://github.com/vmware-tanzu/carvel-secretgen-controller/issues/70 is fixed
    # "DSECRETS_DIR" was removed to support our temporary templateconfig rewrite solution
    ignorePaths:
    - k8s/templates/deployment.star
# END delete
- path: config/carvel-secretgen-controller
  contents:
  - path: .
    githubRelease:
      slug: vmware-tanzu/carvel-secretgen-controller
      tag: v0.10.3
      assetNames: ["release.yml"]
    includePaths:
    - release.yml

# the components in this section below are handled by their corresponding build scripts
# the manual param tells vendir to not override/touch the contents of these config/_ytt_lib/<concourse> directories
- path: config/concourse/_ytt_lib
  contents:
  - path: concourse
    manual: {}

- path: build/concourse/_vendir/
  contents:
  - path: .
    helmChart:
      name: concourse
      version: "17.0.27"
      repository:
        url: https://concourse-charts.storage.googleapis.com/
