---
platform: linux

inputs:
  - name: bosh-community-ci-infra
  - name: director-creds
  - name: jumpbox-creds
  - name: terraform

run:
  path: bosh-community-ci-infra/bosh-concourse/tasks/update-credhub-credentials/update-credhub-credentials.sh
