---
platform: linux

inputs:
  - name: bosh-community-ci-infra

outputs:
  - name: paused-pipelines

params:
  CONCOURSE_URL:
  CONCOURSE_USERNAME: ((concourse_ci_user.username))
  CONCOURSE_PASSWORD: ((concourse_ci_user.password))
  EXCLUDE_PIPELINE: ""
  TEAMS:

run:
  path: bosh-community-ci-infra/bosh-concourse/tasks/deploy-concourse/pause-all-pipelines.sh
