#!/usr/bin/env bash
set -euo pipefail

# List of buckets to update
RELEASE_BUCKETS="bosh-core-stemcells bosh-core-stemcells-fips"
CANDIDATE_BUCKETS="bosh-core-stemcells-candidate bosh-core-stemcells-candidate-fips"

for bucket_name in $RELEASE_BUCKETS; do
    echo "Setting lifecycle policy for bucket: $bucket_name"
    tmpfile=$(mktemp)
    cat <<EOF > "$tmpfile"
{
  "rule": [
    {
      "action": {"type": "Delete"},
      "condition": {"age": 1095}
    }
  ]
}
EOF
    gcloud storage buckets update "gs://$bucket_name" --lifecycle-file="$tmpfile"
    rm -f "$tmpfile"
done

for bucket_name in $CANDIDATE_BUCKETS; do
  echo "Setting lifecycle policy for bucket: $bucket_name"
    tmpfile=$(mktemp)
    cat <<EOF > "$tmpfile"
{
  "rule": [
    {
      "action": {"type": "Delete"},
      "condition": {"age": 365}
    }
  ]
}
EOF
    gcloud storage buckets update "gs://$bucket_name" --lifecycle-file="$tmpfile"
    rm -f "$tmpfile"
done

echo "Done."
