#!/usr/bin/env bash
set -euo pipefail

IMAGES_TO_DELETE=$(gcloud compute images list --filter="name~^stemcell-[a-zA-Z0-9]{8}-" --format="value(name,creationTimestamp)")

if [ -z "$IMAGES_TO_DELETE" ]; then
  echo "No images found matching pattern 'stemcell-<quid>-'."
else
  echo "The following images will be deleted (name, creation date):"
  echo "$IMAGES_TO_DELETE"
  echo "Deleting images..."
  echo "$IMAGES_TO_DELETE" | awk '{print $1}' | xargs gcloud compute images delete --quiet
fi

echo "Done."
