---
- type: replace
  path: /next_nats_server_tls?
  value: ((nats_server_tls))
- type: replace
  path: /nats_server_tls/ca
  value: ((next_nats_server_tls.ca))((nats_ca.ca))
- type: replace
  path: /nats_server_tls/certificate
  value: ((next_nats_server_tls.certificate))
- type: replace
  path: /nats_server_tls/private_key
  value: ((next_nats_server_tls.private_key))
